name: Monitor Cancilleria

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  run-monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install chromium
          playwright install-deps

      - name: Ejecutar script de verificación
        env:
          CEDULA: ${{ secrets.CEDULA }}
          CORREO: ${{ secrets.CORREO }}
          FECHA_EXPEDICION: ${{ secrets.FECHA_EXPEDICION }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        # ⚠️ Asegúrate de que este nombre coincida con tu archivo .py real:
        run: python monitor_cancilleria.py